name: smart_sensor_fusion
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
#  - cudatoolkit=11.7.0      #only install those when there is no cudatoolkit installed
#  - cudatoolkit-dev=11.7.0  #those 2 should not be installed on cluster. use module load cuda/cudnn with respect to pytorch suffix instead!
  - pytorch==2.2.0
  - torchaudio==2.2.0
  - torchvision==0.17.0
  - numpy=1.24.3
  - diffusers=0.18.1
  - hydra-core==1.3.2
  - omegaconf==2.3.0
  - lightning==2.1.2
  - tensorboard==2.15.0
  - matplotlib==3.7.2
  - scikit-learn==1.3.0
  - pandas==2.1.1
  - einops=0.6.1
  - pillow=10.0.1
  - h5py=3.9.0
  - opencv=4.9.0
  - tqdm=4.66.1
  - seaborn=0.12.2
  - setuptools=68.0.0
  - pyaudio==0.2.14
  - librosa==0.10.1
  - pip:
      - einops==0.7.0
      - pyrealsense2==2.54.2.5684