name: 'vit_time_patch_128_51'

model:
  _target_: src.models.progress_prediction.time_patch_model
  preprocess_args:
    length: 40000
    sr: 16000
    n_mels: 128
    norm_audio: False
    hop_ratio: 0.05
  transformer_args:
    model_dim: 64
    num_heads: 2
    num_layers: 2
inference:
  ckpt_path: ' '

