name: 'progress_predictor'

model:
  _target_: src.models.progress_prediction.classification_model
  preprocess_args:
    length: 40000
    sr: 16000
    n_mels: 64
    norm_audio: False
  encoder_args:
    out_dim: 128
  transformer_args:
    channel_size: 128
    model_dim: 512
    input_size: [8, 32]



