# config.yaml


defaults:
- datasets: see_hear_feel_audio
- models: vit
- optimizers: adam_steplr
- pl_modules: progress_predictor
- trainers: progress_predictor
- _self_


# General settings
task_name: "progress_prediction"
seed: 42
results_dir: 'results'
# output dir path: smart_sensor_fusion/results/task name/dataset name/model name/time stamp/
hydra:
  run:
    dir: ./${results_dir}/${task_name}/${datasets.name}/${models.name}${optimizers.name}/time_${now:%m-%d-%H:%M:%S}



