# config_ssl_nce_framework.yaml


defaults:
- datasets: see_hear_feel
- models: diffusion/diffusion_encoder_decoder
- optimizers: adam_steplr
- pl_modules: diffusion/diffusion_policy
- trainers: diffusion
- _self_


# General settings
task_name: "diffusion"
variable_name: trainers.launch_trainer.repeat_trial
output_name: debug
seed: 42
results_dir: 'results'
data_folder_path: '/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/jin4rng/data'

hydra:
  sweeper:
    params:
      trainers.launch_trainer.repeat_trial: 1
      trainers.launch_trainer.max_epochs: 2
#      trainers.launch_trainer.monitor: "val_loss"
      datasets.dataloader.data_folder: ${data_folder_path}
      datasets.dataloader.args.num_stack: 10
      datasets.dataloader.args.len_lb: 10
      models.model.obs_encoder.model_dim: 256
      optimizers: adam_steplr
      datasets.dataloader.batch_size: 16
      pl_modules.pl_module.num_stack: 10
#      models.model.transformer_classifier_args._target_: src.models.vit_implementations.Vit_ClassifierVanillaNoPatch

  sweep:  # didn't use ${hydra.runtime.choices.pl_modules} because "/" \\ if add timestamp: _${now:%m-%d-%H:%M:%S}
    dir: ./${results_dir}/${task_name}/${datasets.name}/${output_name}/${pl_modules.name}_${models.name}_${optimizers.name}/
    # only controls where config.yaml is saved
    subdir: ./
  run: # control where multirun.yaml is saved
    dir: ${hydra.sweep.sub}/.hydra



