# config.yaml


defaults:
- datasets: generate_digits
- models: basic_transformer_multiblocks
- optimizers: adam_steplr
- pl_modules: transpose_predictor
- trainers: transpose_predictor
- _self_


# General settings
task_name: "transpose"
seed: 42
results_dir: 'results'
hydra:
  run:
    dir: ./${results_dir}/${models.name}${optimizers.name}/${datasets.name}/${task_name}${now:%m-%d-%H:%M:%S}test



