name: 'coswarmup'
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 0.001

scheduler:
  _target_: diffusers.optimization.get_cosine_schedule_with_warmup
  num_warmup_steps: 500
  num_training_steps: 5000
