name: 'coswarmup'
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5
  weight_decay: 1e-4

scheduler:
  _target_: diffusers.optimization.get_cosine_schedule_with_warmup
  num_warmup_steps: 990
  num_training_steps: 9900
